function [fitresult, gof] = EEG_startupFilt(EEG)
%CREATEFIT(EEG)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: EEG
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Jun-2022 08:31:36


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], EEG );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [-270.090522408246 3.48956031686754e-06 31.6995726924119 -0.00146830671383357];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


