% function Hd = CMSIS_HPFILT_0_65Hz
%CMSIS_HPFILT_0-65HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 17-Feb-2022 17:55:08

% Elliptic Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = 125;  % Sampling Frequency

N     = 4;     % Order
Fpass = 1;  % Passband Frequency
Apass = 0.5;     % Passband Ripple (dB)
Astop = 40;    % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.highpass('N,Fp,Ast,Ap', N, Fpass, Astop, Apass, Fs);
Hd = design(h, 'ellip');

% [EOF]
% flatten coefficients for ARM
coeffs = reshape(Hd.sosMatrix(:,[1 2 3 5 6])' .* [1 1 1 -1 -1]',[],1);
% create string for copy/paste, cut off last ,\n
coeffStr = sprintf('%1.10ff,\n',coeffs);
clc
disp(coeffStr(1:end-2));